version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '05:00'
    groups:
      ci:
        patterns: ['*']
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '05:00'
    allow:
      - dependency-name: '@actions/*'
    commit-message:
      prefix: build
      include: scope
