name: E2E Runner
on:
  workflow_dispatch:
    inputs:
      runner:
        description: Runner name
        required: false
        type: string
      texlive-version:
        description: TeX Live version
        type: string
        required: true
        default: latest
permissions:
  contents: read
jobs:
  all-nonlatest-runners:
    #
    # Tests on GitHub-hosted runners[^1][^2]
    # - including runners in public preview, but
    # - excluding the `-latest` runners.
    #
    # The `-latest` runners are tested in a separate workflow file[^3].
    #
    # [^1]: <https://github.com/actions/runner-images?tab=readme-ov-file#available-images>
    # [^2]: <https://github.com/actions/partner-runner-images?tab=readme-ov-file#available-images>
    # [^3]: <https://github.com/TeX-Live/setup-texlive-action/blob/main/.github/workflows/e2e.yml>
    #
    if: ${{ !inputs.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-2025
          - windows-11-arm
          - macos-26
          - macos-14
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          version: ${{ inputs.texlive-version }}
      - run: tlmgr version
  single-runner:
    #
    # Tests on the runner specified in the input.
    #
    if: ${{ !!inputs.runner }}
    runs-on: ${{ inputs.runner }}
    name: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          version: ${{ inputs.texlive-version }}
      - run: tlmgr version
